from src.Practice.lesson_14.parser import *

# Я ВЕЛИКИЙ ГРЕШНИК И ПРОШУ У ВАС И ВАШИХ ГЛАЗ ПРОЩЕНИЯ

func_test_sets = [
    (
        "5 + 3 * 8",
        Node(
            terminal=False,
            value="START",
            children=[
                Node(
                    terminal=False,
                    value="T",
                    children=[
                        Node(
                            terminal=False,
                            value="TOKEN",
                            children=[Node(terminal=True, value="5", children=None)],
                        ),
                        Node(
                            terminal=False,
                            value="PROD",
                            children=[Node(terminal=True, value="eps", children=None)],
                        ),
                    ],
                ),
                Node(
                    terminal=False,
                    value="SUM",
                    children=[
                        Node(terminal=True, value="+", children=None),
                        Node(
                            terminal=False,
                            value="T",
                            children=[
                                Node(
                                    terminal=False,
                                    value="TOKEN",
                                    children=[
                                        Node(terminal=True, value="3", children=None)
                                    ],
                                ),
                                Node(
                                    terminal=False,
                                    value="PROD",
                                    children=[
                                        Node(terminal=True, value="*", children=None),
                                        Node(
                                            terminal=False,
                                            value="TOKEN",
                                            children=[
                                                Node(
                                                    terminal=True,
                                                    value="8",
                                                    children=None,
                                                )
                                            ],
                                        ),
                                        Node(
                                            terminal=False,
                                            value="PROD",
                                            children=[
                                                Node(
                                                    terminal=True,
                                                    value="eps",
                                                    children=None,
                                                )
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                        Node(
                            terminal=False,
                            value="SUM",
                            children=[Node(terminal=True, value="eps", children=None)],
                        ),
                    ],
                ),
            ],
        ),
    ),
    (
        "5",
        Node(
            terminal=False,
            value="START",
            children=[
                Node(
                    terminal=False,
                    value="T",
                    children=[
                        Node(
                            terminal=False,
                            value="TOKEN",
                            children=[Node(terminal=True, value="5", children=None)],
                        ),
                        Node(
                            terminal=False,
                            value="PROD",
                            children=[Node(terminal=True, value="eps", children=None)],
                        ),
                    ],
                ),
                Node(
                    terminal=False,
                    value="SUM",
                    children=[Node(terminal=True, value="eps", children=None)],
                ),
            ],
        ),
    ),
    (
        "( 5 + 6 ) * ( 7 + 8 )",
        Node(
            terminal=False,
            value="START",
            children=[
                Node(
                    terminal=False,
                    value="T",
                    children=[
                        Node(
                            terminal=False,
                            value="Token",
                            children=[
                                Node(terminal=True, value="(", children=None),
                                Node(
                                    terminal=False,
                                    value="START",
                                    children=[
                                        Node(
                                            terminal=False,
                                            value="T",
                                            children=[
                                                Node(
                                                    terminal=False,
                                                    value="TOKEN",
                                                    children=[
                                                        Node(
                                                            terminal=True,
                                                            value="5",
                                                            children=None,
                                                        )
                                                    ],
                                                ),
                                                Node(
                                                    terminal=False,
                                                    value="PROD",
                                                    children=[
                                                        Node(
                                                            terminal=True,
                                                            value="eps",
                                                            children=None,
                                                        )
                                                    ],
                                                ),
                                            ],
                                        ),
                                        Node(
                                            terminal=False,
                                            value="SUM",
                                            children=[
                                                Node(
                                                    terminal=True,
                                                    value="+",
                                                    children=None,
                                                ),
                                                Node(
                                                    terminal=False,
                                                    value="T",
                                                    children=[
                                                        Node(
                                                            terminal=False,
                                                            value="TOKEN",
                                                            children=[
                                                                Node(
                                                                    terminal=True,
                                                                    value="6",
                                                                    children=None,
                                                                )
                                                            ],
                                                        ),
                                                        Node(
                                                            terminal=False,
                                                            value="PROD",
                                                            children=[
                                                                Node(
                                                                    terminal=True,
                                                                    value="eps",
                                                                    children=None,
                                                                )
                                                            ],
                                                        ),
                                                    ],
                                                ),
                                                Node(
                                                    terminal=False,
                                                    value="SUM",
                                                    children=[
                                                        Node(
                                                            terminal=True,
                                                            value="eps",
                                                            children=None,
                                                        )
                                                    ],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                                Node(terminal=True, value=")", children=None),
                            ],
                        ),
                        Node(
                            terminal=False,
                            value="PROD",
                            children=[
                                Node(terminal=True, value="*", children=None),
                                Node(
                                    terminal=False,
                                    value="Token",
                                    children=[
                                        Node(terminal=True, value="(", children=None),
                                        Node(
                                            terminal=False,
                                            value="START",
                                            children=[
                                                Node(
                                                    terminal=False,
                                                    value="T",
                                                    children=[
                                                        Node(
                                                            terminal=False,
                                                            value="TOKEN",
                                                            children=[
                                                                Node(
                                                                    terminal=True,
                                                                    value="7",
                                                                    children=None,
                                                                )
                                                            ],
                                                        ),
                                                        Node(
                                                            terminal=False,
                                                            value="PROD",
                                                            children=[
                                                                Node(
                                                                    terminal=True,
                                                                    value="eps",
                                                                    children=None,
                                                                )
                                                            ],
                                                        ),
                                                    ],
                                                ),
                                                Node(
                                                    terminal=False,
                                                    value="SUM",
                                                    children=[
                                                        Node(
                                                            terminal=True,
                                                            value="+",
                                                            children=None,
                                                        ),
                                                        Node(
                                                            terminal=False,
                                                            value="T",
                                                            children=[
                                                                Node(
                                                                    terminal=False,
                                                                    value="TOKEN",
                                                                    children=[
                                                                        Node(
                                                                            terminal=True,
                                                                            value="8",
                                                                            children=None,
                                                                        )
                                                                    ],
                                                                ),
                                                                Node(
                                                                    terminal=False,
                                                                    value="PROD",
                                                                    children=[
                                                                        Node(
                                                                            terminal=True,
                                                                            value="eps",
                                                                            children=None,
                                                                        )
                                                                    ],
                                                                ),
                                                            ],
                                                        ),
                                                        Node(
                                                            terminal=False,
                                                            value="SUM",
                                                            children=[
                                                                Node(
                                                                    terminal=True,
                                                                    value="eps",
                                                                    children=None,
                                                                )
                                                            ],
                                                        ),
                                                    ],
                                                ),
                                            ],
                                        ),
                                        Node(terminal=True, value=")", children=None),
                                    ],
                                ),
                                Node(
                                    terminal=False,
                                    value="PROD",
                                    children=[
                                        Node(terminal=True, value="eps", children=None)
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
                Node(
                    terminal=False,
                    value="SUM",
                    children=[Node(terminal=True, value="eps", children=None)],
                ),
            ],
        ),
    ),
    (
        "( 1 + ( 2 + ( 3 + 7 ) ) )",
        Node(
            terminal=False,
            value="START",
            children=[
                Node(
                    terminal=False,
                    value="T",
                    children=[
                        Node(
                            terminal=False,
                            value="Token",
                            children=[
                                Node(terminal=True, value="(", children=None),
                                Node(
                                    terminal=False,
                                    value="START",
                                    children=[
                                        Node(
                                            terminal=False,
                                            value="T",
                                            children=[
                                                Node(
                                                    terminal=False,
                                                    value="TOKEN",
                                                    children=[
                                                        Node(
                                                            terminal=True,
                                                            value="1",
                                                            children=None,
                                                        )
                                                    ],
                                                ),
                                                Node(
                                                    terminal=False,
                                                    value="PROD",
                                                    children=[
                                                        Node(
                                                            terminal=True,
                                                            value="eps",
                                                            children=None,
                                                        )
                                                    ],
                                                ),
                                            ],
                                        ),
                                        Node(
                                            terminal=False,
                                            value="SUM",
                                            children=[
                                                Node(
                                                    terminal=True,
                                                    value="+",
                                                    children=None,
                                                ),
                                                Node(
                                                    terminal=False,
                                                    value="T",
                                                    children=[
                                                        Node(
                                                            terminal=False,
                                                            value="Token",
                                                            children=[
                                                                Node(
                                                                    terminal=True,
                                                                    value="(",
                                                                    children=None,
                                                                ),
                                                                Node(
                                                                    terminal=False,
                                                                    value="START",
                                                                    children=[
                                                                        Node(
                                                                            terminal=False,
                                                                            value="T",
                                                                            children=[
                                                                                Node(
                                                                                    terminal=False,
                                                                                    value="TOKEN",
                                                                                    children=[
                                                                                        Node(
                                                                                            terminal=True,
                                                                                            value="2",
                                                                                            children=None,
                                                                                        )
                                                                                    ],
                                                                                ),
                                                                                Node(
                                                                                    terminal=False,
                                                                                    value="PROD",
                                                                                    children=[
                                                                                        Node(
                                                                                            terminal=True,
                                                                                            value="eps",
                                                                                            children=None,
                                                                                        )
                                                                                    ],
                                                                                ),
                                                                            ],
                                                                        ),
                                                                        Node(
                                                                            terminal=False,
                                                                            value="SUM",
                                                                            children=[
                                                                                Node(
                                                                                    terminal=True,
                                                                                    value="+",
                                                                                    children=None,
                                                                                ),
                                                                                Node(
                                                                                    terminal=False,
                                                                                    value="T",
                                                                                    children=[
                                                                                        Node(
                                                                                            terminal=False,
                                                                                            value="Token",
                                                                                            children=[
                                                                                                Node(
                                                                                                    terminal=True,
                                                                                                    value="(",
                                                                                                    children=None,
                                                                                                ),
                                                                                                Node(
                                                                                                    terminal=False,
                                                                                                    value="START",
                                                                                                    children=[
                                                                                                        Node(
                                                                                                            terminal=False,
                                                                                                            value="T",
                                                                                                            children=[
                                                                                                                Node(
                                                                                                                    terminal=False,
                                                                                                                    value="TOKEN",
                                                                                                                    children=[
                                                                                                                        Node(
                                                                                                                            terminal=True,
                                                                                                                            value="3",
                                                                                                                            children=None,
                                                                                                                        )
                                                                                                                    ],
                                                                                                                ),
                                                                                                                Node(
                                                                                                                    terminal=False,
                                                                                                                    value="PROD",
                                                                                                                    children=[
                                                                                                                        Node(
                                                                                                                            terminal=True,
                                                                                                                            value="eps",
                                                                                                                            children=None,
                                                                                                                        )
                                                                                                                    ],
                                                                                                                ),
                                                                                                            ],
                                                                                                        ),
                                                                                                        Node(
                                                                                                            terminal=False,
                                                                                                            value="SUM",
                                                                                                            children=[
                                                                                                                Node(
                                                                                                                    terminal=True,
                                                                                                                    value="+",
                                                                                                                    children=None,
                                                                                                                ),
                                                                                                                Node(
                                                                                                                    terminal=False,
                                                                                                                    value="T",
                                                                                                                    children=[
                                                                                                                        Node(
                                                                                                                            terminal=False,
                                                                                                                            value="TOKEN",
                                                                                                                            children=[
                                                                                                                                Node(
                                                                                                                                    terminal=True,
                                                                                                                                    value="7",
                                                                                                                                    children=None,
                                                                                                                                )
                                                                                                                            ],
                                                                                                                        ),
                                                                                                                        Node(
                                                                                                                            terminal=False,
                                                                                                                            value="PROD",
                                                                                                                            children=[
                                                                                                                                Node(
                                                                                                                                    terminal=True,
                                                                                                                                    value="eps",
                                                                                                                                    children=None,
                                                                                                                                )
                                                                                                                            ],
                                                                                                                        ),
                                                                                                                    ],
                                                                                                                ),
                                                                                                                Node(
                                                                                                                    terminal=False,
                                                                                                                    value="SUM",
                                                                                                                    children=[
                                                                                                                        Node(
                                                                                                                            terminal=True,
                                                                                                                            value="eps",
                                                                                                                            children=None,
                                                                                                                        )
                                                                                                                    ],
                                                                                                                ),
                                                                                                            ],
                                                                                                        ),
                                                                                                    ],
                                                                                                ),
                                                                                                Node(
                                                                                                    terminal=True,
                                                                                                    value=")",
                                                                                                    children=None,
                                                                                                ),
                                                                                            ],
                                                                                        ),
                                                                                        Node(
                                                                                            terminal=False,
                                                                                            value="PROD",
                                                                                            children=[
                                                                                                Node(
                                                                                                    terminal=True,
                                                                                                    value="eps",
                                                                                                    children=None,
                                                                                                )
                                                                                            ],
                                                                                        ),
                                                                                    ],
                                                                                ),
                                                                                Node(
                                                                                    terminal=False,
                                                                                    value="SUM",
                                                                                    children=[
                                                                                        Node(
                                                                                            terminal=True,
                                                                                            value="eps",
                                                                                            children=None,
                                                                                        )
                                                                                    ],
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ],
                                                                ),
                                                                Node(
                                                                    terminal=True,
                                                                    value=")",
                                                                    children=None,
                                                                ),
                                                            ],
                                                        ),
                                                        Node(
                                                            terminal=False,
                                                            value="PROD",
                                                            children=[
                                                                Node(
                                                                    terminal=True,
                                                                    value="eps",
                                                                    children=None,
                                                                )
                                                            ],
                                                        ),
                                                    ],
                                                ),
                                                Node(
                                                    terminal=False,
                                                    value="SUM",
                                                    children=[
                                                        Node(
                                                            terminal=True,
                                                            value="eps",
                                                            children=None,
                                                        )
                                                    ],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                                Node(terminal=True, value=")", children=None),
                            ],
                        ),
                        Node(
                            terminal=False,
                            value="PROD",
                            children=[Node(terminal=True, value="eps", children=None)],
                        ),
                    ],
                ),
                Node(
                    terminal=False,
                    value="SUM",
                    children=[Node(terminal=True, value="eps", children=None)],
                ),
            ],
        ),
    ),
]

output_data_set = [
    (
        "( 1 + ( 2 + ( 3 + 7 ) ) )",
        """START
            ...T
            ......Token
            .........(
            .........START
            ............T
            ...............TOKEN
            ..................1
            ...............PROD
            ..................eps
            ............SUM
            ...............+
            ...............T
            ..................Token
            .....................(
            .....................START
            ........................T
            ...........................TOKEN
            ..............................2
            ...........................PROD
            ..............................eps
            ........................SUM
            ...........................+
            ...........................T
            ..............................Token
            .................................(
            .................................START
            ....................................T
            .......................................TOKEN
            ..........................................3
            .......................................PROD
            ..........................................eps
            ....................................SUM
            .......................................+
            .......................................T
            ..........................................TOKEN
            .............................................7
            ..........................................PROD
            .............................................eps
            .......................................SUM
            ..........................................eps
            .................................)
            ..............................PROD
            .................................eps
            ...........................SUM
            ..............................eps
            .....................)
            ..................PROD
            .....................eps
            ...............SUM
            ..................eps
            .........)
            ......PROD
            .........eps
            ...SUM
            ......eps""",
    ),
    (
        "( 5 + 6 ) * ( 7 + 8 )",
        """START
            ...T
            ......Token
            .........(
            .........START
            ............T
            ...............TOKEN
            ..................5
            ...............PROD
            ..................eps
            ............SUM
            ...............+
            ...............T
            ..................TOKEN
            .....................6
            ..................PROD
            .....................eps
            ...............SUM
            ..................eps
            .........)
            ......PROD
            .........*
            .........Token
            ............(
            ............START
            ...............T
            ..................TOKEN
            .....................7
            ..................PROD
            .....................eps
            ...............SUM
            ..................+
            ..................T
            .....................TOKEN
            ........................8
            .....................PROD
            ........................eps
            ..................SUM
            .....................eps
            ............)
            .........PROD
            ............eps
            ...SUM
            ......eps""",
    ),
    (
        "5 + 3 * 8",
        """START
            ...T
            ......TOKEN
            .........5
            ......PROD
            .........eps
            ...SUM
            ......+
            ......T
            .........TOKEN
            ............3
            .........PROD
            ............*
            ............TOKEN
            ...............8
            ............PROD
            ...............eps
            ......SUM
            .........eps""",
    ),
    (
        "5",
        """START
            ...T
            ......TOKEN
            .........5
            ......PROD
            .........eps
            ...SUM
            ......eps""",
    ),
]


func_errors_data_set = [
    ("( 2 + 2", "Error: expected )"),
    ("5 * *", "Error: Unexpected token *\nError: Wrong operation pattern"),
    ("5 + +", "Error: Unexpected token +\nError: Wrong operation pattern"),
]


def func_set_export():
    return func_test_sets


def output_set_export():
    transform_output_data_set = list(
        map(lambda x: (x[0], x[1].replace("            ", "")), output_data_set)
    )
    return transform_output_data_set


def output_errors_export():
    return func_errors_data_set
